// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa71NTlu6KfW-dLVygo8jNNZiPT6MWvGc',
    appId: '1:501620802861:web:a885ebe970c5e72fca3fa4',
    messagingSenderId: '501620802861',
    projectId: 'convertly-c7dbb',
    authDomain: 'convertly-c7dbb.firebaseapp.com',
    storageBucket: 'convertly-c7dbb.firebasestorage.app',
    measurementId: 'G-PWKGJMBYE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sdfhDSAZPdlw_w35Fk4cMm1WpSZMnX8',
    appId: '1:501620802861:android:78cbd245cdef822aca3fa4',
    messagingSenderId: '501620802861',
    projectId: 'convertly-c7dbb',
    storageBucket: 'convertly-c7dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBsvZ0UIuEzxGl13Bl-x7f8wCqIEJnSA',
    appId: '1:501620802861:ios:b3501aec9b884d4aca3fa4',
    messagingSenderId: '501620802861',
    projectId: 'convertly-c7dbb',
    storageBucket: 'convertly-c7dbb.firebasestorage.app',
    iosBundleId: 'com.example.convertly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBsvZ0UIuEzxGl13Bl-x7f8wCqIEJnSA',
    appId: '1:501620802861:ios:b3501aec9b884d4aca3fa4',
    messagingSenderId: '501620802861',
    projectId: 'convertly-c7dbb',
    storageBucket: 'convertly-c7dbb.firebasestorage.app',
    iosBundleId: 'com.example.convertly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa71NTlu6KfW-dLVygo8jNNZiPT6MWvGc',
    appId: '1:501620802861:web:91255ab74c0a1a78ca3fa4',
    messagingSenderId: '501620802861',
    projectId: 'convertly-c7dbb',
    authDomain: 'convertly-c7dbb.firebaseapp.com',
    storageBucket: 'convertly-c7dbb.firebasestorage.app',
    measurementId: 'G-S2Q07VPWKH',
  );

}